# Generated by Django 3.2.7 on 2021-09-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('carmakeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmakeid', to='api_basic.carmake')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('VIN', models.CharField(max_length=10)),
                ('carplate', models.CharField(max_length=10)),
                ('modelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelid', to='api_basic.carmodel')),
            ],
        ),
    ]
