@startuml AppStructure
database "PostgreSQL" 
package "SPA" {
    [React (JS)]
    [Bootstrap]
}

HTTP - [Django Rest Framework (Python)]
[Django Rest Framework (Python)] -> [PostgreSQL]
[React (JS)] ..> [Bootstrap]
[React (JS)] ..> [Django Rest Framework (Python)]
@enduml